/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_crc32 */

#ifndef _Included_liba_crc32
#define _Included_liba_crc32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_crc32
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_crc32_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_crc32
 * Method:    init
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_liba_crc32_init
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     liba_crc32
 * Method:    table
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_liba_crc32_table
  (JNIEnv *, jobject);

/*
 * Class:     liba_crc32
 * Method:    gen
 * Signature: (IZ)Lliba/crc32;
 */
JNIEXPORT jobject JNICALL Java_liba_crc32_gen
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     liba_crc32
 * Method:    eval
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_liba_crc32_eval
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     liba_crc32
 * Method:    pack
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_liba_crc32_pack
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
