/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_pid_fuzzy */

#ifndef _Included_liba_pid_fuzzy
#define _Included_liba_pid_fuzzy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_pid_fuzzy
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_pid_1fuzzy_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_pid_fuzzy
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_pid_1fuzzy_init
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    kp
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_kp
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    set_kp
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1fuzzy_set_1kp
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_fuzzy
 * Method:    ki
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_ki
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    set_ki
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1fuzzy_set_1ki
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_fuzzy
 * Method:    kd
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_kd
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    set_kd
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1fuzzy_set_1kd
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_fuzzy
 * Method:    summax
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_summax
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    set_summax
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1fuzzy_set_1summax
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_fuzzy
 * Method:    summin
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_summin
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    set_summin
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1fuzzy_set_1summin
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_fuzzy
 * Method:    sum
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_sum
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    outmax
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_outmax
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    set_outmax
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1fuzzy_set_1outmax
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_fuzzy
 * Method:    outmin
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_outmin
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    set_outmin
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1fuzzy_set_1outmin
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_fuzzy
 * Method:    out
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_out
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    fdb
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_fdb
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    err
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_err
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    nrule
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_liba_pid_1fuzzy_nrule
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    opr
 * Signature: (I)Lliba/pid_fuzzy;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1fuzzy_opr
  (JNIEnv *, jobject, jint);

/*
 * Class:     liba_pid_fuzzy
 * Method:    nfuzz
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_liba_pid_1fuzzy_nfuzz
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_fuzzy
 * Method:    set_nfuzz
 * Signature: (I)Lliba/pid_fuzzy;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1fuzzy_set_1nfuzz
  (JNIEnv *, jobject, jint);

/*
 * Class:     liba_pid_fuzzy
 * Method:    set_rule
 * Signature: ([[D[[D[[D[[D[[D)Lliba/pid_fuzzy;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1fuzzy_set_1rule
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     liba_pid_fuzzy
 * Method:    set_kpid
 * Signature: (DDD)Lliba/pid_fuzzy;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1fuzzy_set_1kpid
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     liba_pid_fuzzy
 * Method:    run
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_run
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     liba_pid_fuzzy
 * Method:    pos
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_pos
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     liba_pid_fuzzy
 * Method:    inc
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1fuzzy_inc
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     liba_pid_fuzzy
 * Method:    zero
 * Signature: ()Lliba/pid_fuzzy;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1fuzzy_zero
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
