/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_trajpoly7 */

#ifndef _Included_liba_trajpoly7
#define _Included_liba_trajpoly7
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_trajpoly7
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_trajpoly7_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_trajpoly7
 * Method:    c0
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_liba_trajpoly7_c0
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajpoly7
 * Method:    c1
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_liba_trajpoly7_c1
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajpoly7
 * Method:    c2
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_liba_trajpoly7_c2
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajpoly7
 * Method:    c3
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_liba_trajpoly7_c3
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajpoly7
 * Method:    gen
 * Signature: (DDDDDDDDD)Lliba/trajpoly7;
 */
JNIEXPORT jobject JNICALL Java_liba_trajpoly7_gen
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     liba_trajpoly7
 * Method:    pos
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajpoly7_pos
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_trajpoly7
 * Method:    vel
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajpoly7_vel
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_trajpoly7
 * Method:    acc
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajpoly7_acc
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_trajpoly7
 * Method:    jer
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajpoly7_jer
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
