/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_regress_linear */

#ifndef _Included_liba_regress_linear
#define _Included_liba_regress_linear
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_regress_linear
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_regress_1linear_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_regress_linear
 * Method:    init
 * Signature: ([DD)V
 */
JNIEXPORT void JNICALL Java_liba_regress_1linear_init
  (JNIEnv *, jobject, jdoubleArray, jdouble);

/*
 * Class:     liba_regress_linear
 * Method:    coef
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_liba_regress_1linear_coef
  (JNIEnv *, jobject);

/*
 * Class:     liba_regress_linear
 * Method:    set_coef
 * Signature: ([D)Lliba/regress_linear;
 */
JNIEXPORT jobject JNICALL Java_liba_regress_1linear_set_1coef
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     liba_regress_linear
 * Method:    bias
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_regress_1linear_bias
  (JNIEnv *, jobject);

/*
 * Class:     liba_regress_linear
 * Method:    set_bias
 * Signature: (D)Lliba/regress_linear;
 */
JNIEXPORT jobject JNICALL Java_liba_regress_1linear_set_1bias
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_regress_linear
 * Method:    eval
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_regress_1linear_eval
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     liba_regress_linear
 * Method:    err
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_liba_regress_1linear_err
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     liba_regress_linear
 * Method:    gd
 * Signature: ([DDD)Lliba/regress_linear;
 */
JNIEXPORT jobject JNICALL Java_liba_regress_1linear_gd
  (JNIEnv *, jobject, jdoubleArray, jdouble, jdouble);

/*
 * Class:     liba_regress_linear
 * Method:    sgd
 * Signature: ([D[DD)Lliba/regress_linear;
 */
JNIEXPORT jobject JNICALL Java_liba_regress_1linear_sgd
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     liba_regress_linear
 * Method:    bgd
 * Signature: ([D[DD)Lliba/regress_linear;
 */
JNIEXPORT jobject JNICALL Java_liba_regress_1linear_bgd
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     liba_regress_linear
 * Method:    mgd
 * Signature: ([D[DDDDIII)D
 */
JNIEXPORT jdouble JNICALL Java_liba_regress_1linear_mgd
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdouble, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     liba_regress_linear
 * Method:    zero
 * Signature: ()Lliba/regress_linear;
 */
JNIEXPORT jobject JNICALL Java_liba_regress_1linear_zero
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
