/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_mf */

#ifndef _Included_liba_mf
#define _Included_liba_mf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_mf
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_mf_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_mf
 * Method:    gauss
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_gauss
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     liba_mf
 * Method:    gauss2
 * Signature: (DDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_gauss2
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     liba_mf
 * Method:    gbell
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_gbell
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     liba_mf
 * Method:    sig
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_sig
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     liba_mf
 * Method:    dsig
 * Signature: (DDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_dsig
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     liba_mf
 * Method:    psig
 * Signature: (DDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_psig
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     liba_mf
 * Method:    trap
 * Signature: (DDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_trap
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     liba_mf
 * Method:    tri
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_tri
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     liba_mf
 * Method:    lins
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_lins
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     liba_mf
 * Method:    linz
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_linz
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     liba_mf
 * Method:    s
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_s
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     liba_mf
 * Method:    z
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_z
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     liba_mf
 * Method:    pi
 * Signature: (DDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_mf_pi
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
