/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_lpf */

#ifndef _Included_liba_lpf
#define _Included_liba_lpf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_lpf
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_lpf_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_lpf
 * Method:    init
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_liba_lpf_init
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     liba_lpf
 * Method:    alpha
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_lpf_alpha
  (JNIEnv *, jobject);

/*
 * Class:     liba_lpf
 * Method:    output
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_lpf_output
  (JNIEnv *, jobject);

/*
 * Class:     liba_lpf
 * Method:    gen
 * Signature: (DD)Lliba/lpf;
 */
JNIEXPORT jobject JNICALL Java_liba_lpf_gen
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     liba_lpf
 * Method:    iter
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_lpf_iter
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_lpf
 * Method:    zero
 * Signature: ()Lliba/lpf;
 */
JNIEXPORT jobject JNICALL Java_liba_lpf_zero
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
