/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_crc64 */

#ifndef _Included_liba_crc64
#define _Included_liba_crc64
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_crc64
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_crc64_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_crc64
 * Method:    init
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_liba_crc64_init
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     liba_crc64
 * Method:    table
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_liba_crc64_table
  (JNIEnv *, jobject);

/*
 * Class:     liba_crc64
 * Method:    gen
 * Signature: (JZ)Lliba/crc64;
 */
JNIEXPORT jobject JNICALL Java_liba_crc64_gen
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     liba_crc64
 * Method:    eval
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_liba_crc64_eval
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     liba_crc64
 * Method:    pack
 * Signature: ([BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_liba_crc64_pack
  (JNIEnv *, jobject, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
