/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_crc16 */

#ifndef _Included_liba_crc16
#define _Included_liba_crc16
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_crc16
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_crc16_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_crc16
 * Method:    init
 * Signature: (SZ)V
 */
JNIEXPORT void JNICALL Java_liba_crc16_init
  (JNIEnv *, jobject, jshort, jboolean);

/*
 * Class:     liba_crc16
 * Method:    table
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_liba_crc16_table
  (JNIEnv *, jobject);

/*
 * Class:     liba_crc16
 * Method:    gen
 * Signature: (SZ)Lliba/crc16;
 */
JNIEXPORT jobject JNICALL Java_liba_crc16_gen
  (JNIEnv *, jobject, jshort, jboolean);

/*
 * Class:     liba_crc16
 * Method:    eval
 * Signature: ([BS)S
 */
JNIEXPORT jshort JNICALL Java_liba_crc16_eval
  (JNIEnv *, jobject, jbyteArray, jshort);

/*
 * Class:     liba_crc16
 * Method:    pack
 * Signature: ([BS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_liba_crc16_pack
  (JNIEnv *, jobject, jbyteArray, jshort);

#ifdef __cplusplus
}
#endif
#endif
