/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba */

#ifndef _Included_liba
#define _Included_liba
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba
 * Method:    isqrt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_liba_isqrt__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     liba
 * Method:    isqrt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_liba_isqrt__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     liba
 * Method:    rsqrt
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_liba_rsqrt__F
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     liba
 * Method:    rsqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_rsqrt__D
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     liba
 * Method:    hash_bkdr
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_liba_hash_1bkdr
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     liba
 * Method:    hash_sdbm
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_liba_hash_1sdbm
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
