/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_hpf */

#ifndef _Included_liba_hpf
#define _Included_liba_hpf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_hpf
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_hpf_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_hpf
 * Method:    init
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_liba_hpf_init
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     liba_hpf
 * Method:    alpha
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_hpf_alpha
  (JNIEnv *, jobject);

/*
 * Class:     liba_hpf
 * Method:    output
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_hpf_output
  (JNIEnv *, jobject);

/*
 * Class:     liba_hpf
 * Method:    input
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_hpf_input
  (JNIEnv *, jobject);

/*
 * Class:     liba_hpf
 * Method:    gen
 * Signature: (DD)Lliba/hpf;
 */
JNIEXPORT jobject JNICALL Java_liba_hpf_gen
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     liba_hpf
 * Method:    iter
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_hpf_iter
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_hpf
 * Method:    zero
 * Signature: ()Lliba/hpf;
 */
JNIEXPORT jobject JNICALL Java_liba_hpf_zero
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
