/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_trajbell */

#ifndef _Included_liba_trajbell
#define _Included_liba_trajbell
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_trajbell
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_trajbell_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_trajbell
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_trajbell_init
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    t
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_t
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    tv
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_tv
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    ta
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_ta
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    td
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_td
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    taj
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_taj
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    tdj
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_tdj
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    p0
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_p0
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    p1
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_p1
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    v0
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_v0
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    v1
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_v1
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    vm
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_vm
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    jm
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_jm
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    am
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_am
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    dm
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_dm
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajbell
 * Method:    gen
 * Signature: (DDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_gen
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     liba_trajbell
 * Method:    pos
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_pos
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_trajbell
 * Method:    vel
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_vel
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_trajbell
 * Method:    acc
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_acc
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_trajbell
 * Method:    jer
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajbell_jer
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
