/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_tf */

#ifndef _Included_liba_tf
#define _Included_liba_tf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_tf
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_tf_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_tf
 * Method:    init
 * Signature: ([D[D)V
 */
JNIEXPORT void JNICALL Java_liba_tf_init
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     liba_tf
 * Method:    num
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_liba_tf_num
  (JNIEnv *, jobject);

/*
 * Class:     liba_tf
 * Method:    set_num
 * Signature: ([D)Lliba/tf;
 */
JNIEXPORT jobject JNICALL Java_liba_tf_set_1num
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     liba_tf
 * Method:    den
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_liba_tf_den
  (JNIEnv *, jobject);

/*
 * Class:     liba_tf
 * Method:    set_den
 * Signature: ([D)Lliba/tf;
 */
JNIEXPORT jobject JNICALL Java_liba_tf_set_1den
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     liba_tf
 * Method:    input
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_liba_tf_input
  (JNIEnv *, jobject);

/*
 * Class:     liba_tf
 * Method:    output
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_liba_tf_output
  (JNIEnv *, jobject);

/*
 * Class:     liba_tf
 * Method:    iter
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_tf_iter
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_tf
 * Method:    zero
 * Signature: ()Lliba/tf;
 */
JNIEXPORT jobject JNICALL Java_liba_tf_zero
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
