/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_trajtrap */

#ifndef _Included_liba_trajtrap
#define _Included_liba_trajtrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_trajtrap
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_trajtrap_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_trajtrap
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_trajtrap_init
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    t
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_t
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    p0
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_p0
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    p1
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_p1
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    v0
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_v0
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    v1
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_v1
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    vc
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_vc
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    ta
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_ta
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    td
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_td
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    pa
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_pa
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    pd
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_pd
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    ac
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_ac
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    de
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_de
  (JNIEnv *, jobject);

/*
 * Class:     liba_trajtrap
 * Method:    gen
 * Signature: (DDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_gen
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     liba_trajtrap
 * Method:    pos
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_pos
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_trajtrap
 * Method:    vel
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_vel
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_trajtrap
 * Method:    acc
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_liba_trajtrap_acc
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
