/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class liba_pid_neuro */

#ifndef _Included_liba_pid_neuro
#define _Included_liba_pid_neuro
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     liba_pid_neuro
 * Method:    clinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_pid_1neuro_clinit
  (JNIEnv *, jclass);

/*
 * Class:     liba_pid_neuro
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_liba_pid_1neuro_init
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    k
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_k
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    set_k
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1neuro_set_1k
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    kp
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_kp
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    set_kp
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1neuro_set_1kp
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    ki
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_ki
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    set_ki
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1neuro_set_1ki
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    kd
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_kd
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    set_kd
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1neuro_set_1kd
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    wp
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_wp
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    set_wp
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1neuro_set_1wp
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    wi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_wi
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    set_wi
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1neuro_set_1wi
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    wd
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_wd
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    set_wd
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1neuro_set_1wd
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    outmax
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_outmax
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    set_outmax
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1neuro_set_1outmax
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    outmin
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_outmin
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    set_outmin
 * Signature: (D)Lliba/pid;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1neuro_set_1outmin
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    out
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_out
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    fdb
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_fdb
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    err
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_err
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    ec
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_ec
  (JNIEnv *, jobject);

/*
 * Class:     liba_pid_neuro
 * Method:    set_kpid
 * Signature: (DDDD)Lliba/pid_neuro;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1neuro_set_1kpid
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    set_wpid
 * Signature: (DDD)Lliba/pid_neuro;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1neuro_set_1wpid
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    run
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_run
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    inc
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_liba_pid_1neuro_inc
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     liba_pid_neuro
 * Method:    zero
 * Signature: ()Lliba/pid_neuro;
 */
JNIEXPORT jobject JNICALL Java_liba_pid_1neuro_zero
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
