local subprocess = require("bee.subprocess")
local fs = require("bee.filesystem")
local luamake = fs.exe_path()
assert(subprocess.spawn({ luamake, "lua", "test/a.lua" })):wait()
assert(subprocess.spawn({ luamake, "lua", "test/complex.lua" })):wait()
assert(subprocess.spawn({ luamake, "lua", "test/mf.lua" })):wait()
assert(subprocess.spawn({ luamake, "lua", "test/pid.lua" })):wait()
assert(subprocess.spawn({ luamake, "lua", "test/pid_fuzzy.lua" })):wait()
assert(subprocess.spawn({ luamake, "lua", "test/pid_neuro.lua" })):wait()
assert(subprocess.spawn({ luamake, "lua", "test/polytraj3.lua" })):wait()
assert(subprocess.spawn({ luamake, "lua", "test/polytraj5.lua" })):wait()
assert(subprocess.spawn({ luamake, "lua", "test/polytraj7.lua" })):wait()
assert(subprocess.spawn({ luamake, "lua", "test/tf.lua" })):wait()
assert(subprocess.spawn({ luamake, "lua", "test/traptraj.lua" })):wait()
assert(subprocess.spawn({ luamake, "lua", "test/version.lua" })):wait()
