#!/usr/bin/env sh
cd $(dirname $0)

mkdir -p ../build
cp config.h.in configure.ac ../build
cd ..
cp -r src include/a build
cd build

for i in $(find a -regex ".*\.\(h\|hh\)"); do
    HEADERS="$HEADERS $i"
done

for i in $(find src -regex ".*\.\(c\|h\)"); do
    C_SOURCES="$C_SOURCES $i"
done

for i in $(find src -regex ".*\.\(cc\|hh\)"); do
    CXX_SOURCES="$CXX_SOURCES $i"
done

echo "ACLOCAL_AMFLAGS = -I m4
lib_LTLIBRARIES = liba.la
liba_la_CPPFLAGS = -std=c11
liba_la_LDFLAGS = -version-info 1:7:1
liba_la_SOURCES =$C_SOURCES autogen.sh
liba_la_LIBADD = \$(liba_cc_la_OBJECTS)
noinst_LTLIBRARIES = liba.cc.la
liba_cc_la_CPPFLAGS = -std=c++11
liba_cc_la_SOURCES =$CXX_SOURCES
nobase_include_HEADERS =$HEADERS
install-data-hook:
	\$(INSTALL_DATA) config.h \$(DESTDIR)\$(includedir)/a
	@sed -i 's|#if defined(A_HAVE_H)|#include \"config.h\"\\\\n#if defined(A_HAVE_H)|g' \$(DESTDIR)\$(includedir)/a/a.h
uninstall-hook:
	\$(RM) \$(DESTDIR)\$(includedir)/a/config.h" > Makefile.am

echo "libtoolize -Wall -ci
aclocal -Wall
autoreconf -Wall
automake -Wall --add-missing
if [ -f config.h.in~ ] && [ -f config.h.in ]; then
    mv config.h.in~ config.h.in
fi" > autogen.sh
chmod +x autogen.sh
./autogen.sh
./configure
make distcheck dist-xz
