#!/usr/bin/env bash
IFS=$'\n'
sources=$(find include src test lua/src java/src quickjs/src javascript/src -regex ".*\.\(c\|h\|cc\|hh\|cpp\|hpp\|cxx\|hxx\)")
clang-format -style=file -i $sources --verbose
black .
