#!/usr/bin/env node
var liba = require("../liba")
console.log("version", liba.VERSION)
console.log("major", liba.VERSION_MAJOR)
console.log("minor", liba.VERSION_MINOR)
console.log("patch", liba.VERSION_PATCH)
console.log("tweak", liba.VERSION_TWEAK)
var v = new liba.version()
console.log(v.toString())
var v = new liba.version(1)
console.log(v.toString())
var v = new liba.version(1, 2)
console.log(v.toString())
var v = new liba.version(1, 2, 3)
console.log(v.parse("3.2.1").toString())
console.log(liba.version_check(0, 0, 0))
console.log(v.cmp(new liba.version(1, 2, 0)))
