#!/usr/bin/env node
var liba = require("../liba")
console.log("version", liba.VERSION)
console.log("major", liba.version.MAJOR)
console.log("minor", liba.version.MINOR)
console.log("patch", liba.version.PATCH)
console.log("tweak", liba.version.TWEAK)
var v = new liba.version()
console.log(v.toString())
var v = new liba.version(1)
console.log(v.toString())
var v = new liba.version(1, 2)
console.log(v.toString())
var v = new liba.version(1, 2, 3)
console.log(v.major, v.minor, v.patch)
console.log(v.parse("3.2.1").toString())
console.log(liba.version.check(0, 0, 0))
console.log(v.cmp(new liba.version(1, 2, 0)))
v.major = v.minor = v.patch = 0
