#!/usr/bin/env node
var Module = require("../liba.js")
console.log(Module.VERSION_MAJOR)
console.log(Module.VERSION_MINOR)
console.log(Module.VERSION_PATCH)
console.log(Module.VERSION)
var v = new Module.version()
console.log(v.str())
var v = new Module.version(1)
console.log(v.str())
var v = new Module.version(1, 2)
console.log(v.str())
var v = new Module.version(1, 2, 3)
console.log(v.str())
console.log(Module.version_check(0, 0, 0))
console.log(v.cmp(new Module.version(1, 2, 0)))
