function(QUICKJS_PIC)
  set(CMAKETMP ${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp)
  file(WRITE ${CMAKETMP}/module.c "#include \"quickjs.h\"
JSModuleDef *js_init_module(JSContext *const ctx, char const *const module_name)
{\n\treturn JS_NewCModule(ctx, module_name, 0);\n}
")
  file(WRITE ${CMAKETMP}/CMakeLists.txt "cmake_minimum_required(VERSION ${CMAKE_VERSION})
project(CMAKE_TRY_COMPILE C)\nadd_library(module SHARED module.c)
target_include_directories(module PRIVATE ${QUICKJS_INCLUDE_DIR})
target_link_libraries(module PRIVATE ${QUICKJS_LIBRARIES})
")
  try_compile(QUICKJS_PIC ${CMAKETMP} ${CMAKETMP} CMAKE_TRY_COMPILE)
  if(QUICKJS_PIC)
    set(QUICKJS_PIC 1 CACHE INTERNAL "QuickJS complied with PIC")
  else()
    set(QUICKJS_PIC 0 CACHE INTERNAL "QuickJS complied with PIC")
  endif()
  file(REMOVE_RECURSE ${CMAKETMP})
endfunction()
if(NOT DEFINED QUICKJS_PIC)
  QUICKJS_PIC()
endif()
