set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

find_program(CMAKE_AR ${TOOLCHAIN_PREFIX}-gcc-ar)
find_program(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
find_program(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
find_program(CMAKE_RANLIB ${TOOLCHAIN_PREFIX}-gcc-ranlib)
find_program(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)
find_program(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_PREFIX}-gcc NO_CACHE)
get_filename_component(CMAKE_FIND_ROOT_PATH "${CMAKE_FIND_ROOT_PATH}" DIRECTORY)
get_filename_component(CMAKE_FIND_ROOT_PATH "${CMAKE_FIND_ROOT_PATH}" DIRECTORY)

if(UNIX)
  set(CMAKE_FIND_ROOT_PATH "${CMAKE_FIND_ROOT_PATH}/${TOOLCHAIN_PREFIX}")
  find_program(CMAKE_CROSSCOMPILING_EMULATOR wine64)
  if(NOT CMAKE_CROSSCOMPILING_EMULATOR)
    unset(CMAKE_CROSSCOMPILING_EMULATOR CACHE)
  endif()
endif()

set(CMAKE_INSTALL_PREFIX ${CMAKE_FIND_ROOT_PATH} CACHE PATH
  "Install path prefix, prepended onto install directories."
)

if(NOT WIN32)
  set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
  set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()

if(DEFINED CACHE{CMAKE_FIND_ROOT_PATH})
  unset(CMAKE_FIND_ROOT_PATH CACHE)
endif()
