import * as a from "liba.so";
var ctx = new a.hpf(10, 0.01)
ctx.gen(10, 0.01)
ctx.iter(1)
console.log(ctx.alpha)
console.log(ctx.output)
console.log(ctx.input)
var ctx = new a.hpf(0.1)
ctx.gen(0.1)
ctx.iter(1)
console.log(ctx.alpha)
console.log(ctx.output)
console.log(ctx.input)
ctx.zero()
